[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^4.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
